import { IconBootstrap } from '@/components/icons/icon-bootstrap';
import { IconChakraUi } from '@/components/icons/icon-chakra-ui';
import { IconComposer } from '@/components/icons/icon-composer';
import { IconDocker } from '@/components/icons/icon-docker';
import { IconFigma } from '@/components/icons/icon-figma';
import { IconGit } from '@/components/icons/icon-git';
import { IconLaravel } from '@/components/icons/icon-laravel';
import { IconNextJs } from '@/components/icons/icon-next-js';
import { IconNodejs } from '@/components/icons/icon-node-js';
import { IconNpm } from '@/components/icons/icon-npm';
import { IconNuxtJs } from '@/components/icons/icon-nuxt-js';
import { IconReact } from '@/components/icons/icon-react';
import { IconSass } from '@/components/icons/icon-sass';
import { IconTailwind } from '@/components/icons/icon-tailwind';
import { IconTypescript } from '@/components/icons/icon-typecript';
import { IconVite } from '@/components/icons/icon-vite';
import { IconVue } from '@/components/icons/icon-vue';
import { IconYarn } from '@/components/icons/icon-yarn';

export const STACK_CATEGORIES: Array<StackCategory> = [
  {
    name: 'Backend',
    description: [''],
    slug: 'backend',
    tags: [],
    tools: [
      {
        name: 'PHP',
        description: [''],
        parent: 'backend',
        proficiency: 8,
        slug: 'php',
        type: 'Programming Language',
        style: { x: 426.5, y: 488.5, size: 62.5 },
      },
      {
        name: 'Laravel',
        icon: IconLaravel,
        description: [''],
        parent: 'backend',
        proficiency: 8,
        slug: 'laravel',
        type: 'Language Framework',
        style: { x: 533, y: 570, size: 50 },
      },
      {
        name: 'Node js',
        icon: IconNodejs,
        description: [''],
        parent: 'backend',
        proficiency: 7,
        slug: 'nodejs',
        type: 'Programming Language',
        style: { x: 344.5, y: 558.5, size: 37.5 },
      },
      {
        name: 'Adonis js',
        description: [''],
        parent: 'backend',
        proficiency: 7,
        slug: 'adonisjs',
        type: 'Language Framework',
        style: { x: 413.5, y: 619.5, size: 37.5 },
      },
      {
        name: 'MySQL',
        description: [''],
        parent: 'backend',
        proficiency: 9,
        slug: 'mysql',
        type: 'Database Engine',
        style: { x: 279, y: 657, size: 25 },
      },
      {
        name: 'Sails js',
        description: [''],
        parent: 'backend',
        proficiency: 7,
        slug: 'sailsjs',
        type: 'Language Framework',
        style: { x: 348, y: 652, size: 25 },
      },
      {
        name: 'Redis',
        description: [''],
        parent: 'backend',
        proficiency: 6,
        slug: 'redis',
        type: 'Database Engine',
        style: { x: 454.5, y: 570.5, size: 17.5 },
      },
      {
        name: 'MongoDB',
        description: [''],
        parent: 'backend',
        proficiency: 5,
        slug: 'mongodb',
        type: 'Database Engine',
        style: { x: 283, y: 608, size: 16 },
      },
      {
        name: 'Express js',
        description: [''],
        parent: 'backend',
        proficiency: 9,
        slug: 'expressjs',
        type: 'Language Framework',
        style: { x: 320, y: 616, size: 16 },
      },
      {
        name: 'Phpunit',
        description: [''],
        parent: 'backend',
        proficiency: 10,
        slug: 'phpunit',
        type: 'Software Testing',
        style: { x: 510, y: 497, size: 12 },
      },
      {
        name: 'GraphQL',
        description: [''],
        parent: 'backend',
        proficiency: 4,
        slug: 'graphql',
        type: 'API Language',
        style: { x: 471, y: 620, size: 12 },
      },
      {
        name: 'REST API',
        description: [''],
        parent: 'backend',
        proficiency: 10,
        slug: 'rest',
        type: 'API Language',
        style: { x: 471, y: 620, size: 12 },
      },
    ],
  },
  {
    name: 'Frontend',
    description: [''],
    slug: 'frontend',
    tags: [],
    tools: [
      {
        name: 'JavaScript',
        description: [''],
        parent: 'frontend',
        proficiency: 8,
        slug: 'javascript',
        type: 'Programming Language',
        style: { x: 289, y: 209, size: 75 },
      },
      {
        name: 'CSS',
        description: [''],
        parent: 'frontend',
        proficiency: 10,
        slug: 'css',
        type: 'Programming Language',
        style: { x: 444, y: 202, size: 70 },
      },
      {
        name: 'Vue.js',
        icon: IconVue,
        description: [''],
        parent: 'frontend',
        proficiency: 9,
        slug: 'vue',
        type: 'Language Framework',
        style: { x: 402, y: 66, size: 63 },
      },
      {
        name: 'Typescript',
        icon: IconTypescript,
        description: [''],
        parent: 'frontend',
        proficiency: 8,
        slug: 'typescript',
        type: 'Programming Language',
        style: { x: 295.5, y: 79.5, size: 37.5 },
      },
      {
        name: 'React',
        icon: IconReact,
        description: [''],
        parent: 'frontend',
        proficiency: 9,
        slug: 'react',
        type: 'Language Framework',
        style: { x: 518, y: 94, size: 50 },
      },
      {
        name: 'SASS',
        icon: IconSass,
        description: [''],
        parent: 'frontend',
        proficiency: 8,
        slug: 'sass',
        type: 'Programming Language',
        style: { x: 132, y: 140, size: 34 },
      },
      {
        name: 'Tailwindcss',
        icon: IconTailwind,
        description: [''],
        parent: 'frontend',
        proficiency: 10,
        slug: 'tailwindcss',
        type: 'Language Framework',
        style: { x: 215, y: 61, size: 34 },
      },
      {
        name: 'Nuxt JS',
        icon: IconNuxtJs,
        description: [''],
        parent: 'frontend',
        proficiency: 8,
        slug: 'nuxtjs',
        type: 'Language Framework',
        style: { x: 582, y: 186, size: 27 },
      },
      {
        name: 'Next.js',
        icon: IconNextJs,
        description: [''],
        parent: 'frontend',
        proficiency: 7,
        slug: 'nextjs',
        type: 'Language Framework',
        style: { x: 186, y: 176, size: 24 },
      },
      {
        name: 'Chakra UI',
        icon: IconChakraUi,
        description: [''],
        parent: 'frontend',
        proficiency: 8,
        slug: 'chakra-ui',
        type: 'Language Framework',
        style: { x: 225, y: 123, size: 23 },
      },
      {
        name: 'Bootstrap',
        icon: IconBootstrap,
        description: [''],
        parent: 'frontend',
        proficiency: 8,
        slug: 'bootstrap',
        type: 'Language Framework',
        style: { x: 316, y: 24, size: 16 },
      },
      {
        name: 'Vitest',
        description: [''],
        parent: 'frontend',
        proficiency: 7,
        slug: 'vitest',
        type: 'Software Testing',
        style: { x: 575, y: 138, size: 16 },
      },
      {
        name: 'Jest',
        description: [''],
        parent: 'frontend',
        proficiency: 7,
        slug: 'jest',
        type: 'Software Testing',
        style: { x: 535, y: 173, size: 16 },
      },
      {
        name: 'JQuery',
        description: [''],
        parent: 'frontend',
        proficiency: 10,
        slug: 'jquery',
        type: 'Code Library',
        style: { x: 351, y: 130, size: 12 },
      },
      {
        name: 'React Native',
        description: [''],
        parent: 'frontend',
        proficiency: 6,
        slug: 'react-native',
        type: 'Language Framework',
        style: { x: 174, y: 106, size: 12 },
      },
    ],
  },
  {
    name: 'Cloud & OS',
    description: [''],
    slug: 'cloud',
    tags: [],
    tools: [
      {
        name: 'Github',
        description: [''],
        parent: 'cloud',
        proficiency: 8,
        slug: 'github',
        type: 'Code Repository',
        style: { x: 78, y: 301, size: 60 },
      },
      {
        name: 'Vercel',
        description: [''],
        parent: 'cloud',
        proficiency: 8,
        slug: 'vercel',
        type: 'cloud',
        style: { x: 172, y: 400, size: 48 },
      },
      {
        name: 'Gitlab',
        description: [''],
        parent: 'cloud',
        proficiency: 7,
        slug: 'gitlab',
        type: 'Code Repository',
        style: { x: 36, y: 398, size: 36 },
      },
      {
        name: 'Linux',
        description: [''],
        parent: 'cloud',
        proficiency: 7,
        slug: 'linux',
        type: 'Operating system',
        style: { x: 94, y: 435, size: 27 },
      },
      {
        name: 'Apache',
        description: [''],
        parent: 'cloud',
        proficiency: 7,
        slug: 'apache',
        type: 'HTTP Server',
        style: { x: 210, y: 324, size: 24 },
      },
      {
        name: 'AWS',
        description: [''],
        parent: 'cloud',
        proficiency: 5,
        slug: 'aws',
        type: 'cloud',
        style: { x: 63, y: 214, size: 21 },
      },
      {
        name: 'Netlify',
        description: [''],
        parent: 'cloud',
        proficiency: 5,
        slug: 'netlify',
        type: 'cloud',
        style: { x: 148, y: 249, size: 21 },
      },
      {
        name: 'Nginx',
        description: [''],
        parent: 'cloud',
        proficiency: 7,
        slug: 'nginx',
        type: 'HTTP Server',
        style: { x: 47, y: 457, size: 20 },
      },
      {
        name: 'Docker',
        icon: IconDocker,
        description: [''],
        parent: 'cloud',
        proficiency: 5,
        slug: 'docker',
        type: 'Code Repository',
        style: { x: 161, y: 311, size: 18 },
      },
      {
        name: 'Digital Ocean',
        description: [''],
        parent: 'cloud',
        proficiency: 6,
        slug: 'digitalocean',
        type: 'cloud',
        style: { x: 94, y: 386, size: 16 },
      },
      {
        name: 'Windows',
        description: [''],
        parent: 'cloud',
        proficiency: 7,
        slug: 'windows',
        type: 'Operating system',
        style: { x: 102, y: 226, size: 12 },
      },
      {
        name: 'Mac OS',
        description: [''],
        parent: 'cloud',
        proficiency: 8,
        slug: 'macos',
        type: 'Operating system',
        style: { x: 178, y: 276, size: 12 },
      },
    ],
  },
  {
    name: 'Product Design & Management',
    description: [''],
    slug: 'design',
    tags: [],
    tools: [
      {
        name: 'Figma',
        icon: IconFigma,
        description: [''],
        parent: 'design',
        proficiency: 9,
        slug: 'figma',
        type: 'Design & Prototyping',
        style: { x: 141, y: 562, size: 50 },
      },
      {
        name: 'Jira',
        description: [''],
        parent: 'design',
        proficiency: 7,
        slug: 'jira',
        type: 'product-tracking',
        style: { x: 196, y: 628, size: 30 },
      },
      {
        name: 'Slack',
        description: [''],
        parent: 'design',
        proficiency: 10,
        slug: 'slack',
        type: 'Communication',
        style: { x: 161, y: 489, size: 20 },
      },
      {
        name: 'Asana',
        description: [''],
        parent: 'design',
        proficiency: 6,
        slug: 'asana',
        type: 'product-tracking',
        style: { x: 225, y: 565, size: 20 },
      },
      {
        name: 'Whimsical',
        description: [''],
        parent: 'design',
        proficiency: 8,
        slug: 'whimsical',
        type: 'Design & Prototyping',
        style: { x: 205, y: 517, size: 15 },
      },
    ],
  },
  {
    name: 'Package and Dependency Management',
    description: [''],
    slug: 'package_management',
    tags: [],
    tools: [
      {
        name: 'NPM',
        icon: IconNpm,
        description: [''],
        parent: 'package_management',
        proficiency: 10,
        slug: 'npm',
        type: 'Dependency Management',
        style: { x: 544, y: 349, size: 60 },
      },
      {
        name: 'Git',
        icon: IconGit,
        description: [''],
        parent: 'package_management',
        proficiency: 8,
        slug: 'git',
        type: 'Version Control',
        style: { x: 648, y: 301, size: 49 },
      },
      {
        name: 'Vite',
        icon: IconVite,
        description: [''],
        parent: 'package_management',
        proficiency: 8,
        slug: 'vite',
        type: 'Asset Bundler',
        style: { x: 652, y: 420, size: 36 },
      },
      {
        name: 'PNPM',
        description: [''],
        parent: 'package_management',
        proficiency: 10,
        slug: 'pnpm',
        type: 'Dependency Management',
        style: { x: 580, y: 441, size: 26 },
      },
      {
        name: 'Webpack',
        description: [''],
        parent: 'package_management',
        proficiency: 7,
        slug: 'webpack',
        type: 'Asset Bundler',
        style: { x: 623, y: 370, size: 16 },
      },
      {
        name: 'Yarn',
        icon: IconYarn,
        description: [''],
        parent: 'package_management',
        proficiency: 7,
        slug: 'yarn',
        type: 'Dependency Management',
        style: { x: 667, y: 365, size: 12 },
      },
      {
        name: 'Composer',
        icon: IconComposer,
        description: [''],
        parent: 'package_management',
        proficiency: 8,
        slug: 'composer',
        type: 'Dependency Management',
        style: { x: 583, y: 280, size: 12 },
      },
    ],
  },
];
