/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _homeRouteRouteImport } from './routes/__home/route'
import { Route as _homeIndexRouteImport } from './routes/__home/index'
import { Route as _homeTimelineRouteImport } from './routes/__home/timeline'
import { Route as _homeMyStackRouteImport } from './routes/__home/my-stack'
import { Route as _homeMySocialsRouteImport } from './routes/__home/my-socials'
import { Route as _homeMyProjectsRouteImport } from './routes/__home/my-projects'
import { Route as _homeMyBioRouteImport } from './routes/__home/my-bio'
import { Route as _homeGamingRouteImport } from './routes/__home/gaming'
import { Route as _homeContactMeRouteImport } from './routes/__home/contact-me'

const _homeRouteRoute = _homeRouteRouteImport.update({
  id: '/__home',
  getParentRoute: () => rootRouteImport,
} as any)
const _homeIndexRoute = _homeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _homeRouteRoute,
} as any)
const _homeTimelineRoute = _homeTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => _homeRouteRoute,
} as any)
const _homeMyStackRoute = _homeMyStackRouteImport.update({
  id: '/my-stack',
  path: '/my-stack',
  getParentRoute: () => _homeRouteRoute,
} as any)
const _homeMySocialsRoute = _homeMySocialsRouteImport.update({
  id: '/my-socials',
  path: '/my-socials',
  getParentRoute: () => _homeRouteRoute,
} as any)
const _homeMyProjectsRoute = _homeMyProjectsRouteImport.update({
  id: '/my-projects',
  path: '/my-projects',
  getParentRoute: () => _homeRouteRoute,
} as any)
const _homeMyBioRoute = _homeMyBioRouteImport.update({
  id: '/my-bio',
  path: '/my-bio',
  getParentRoute: () => _homeRouteRoute,
} as any)
const _homeGamingRoute = _homeGamingRouteImport.update({
  id: '/gaming',
  path: '/gaming',
  getParentRoute: () => _homeRouteRoute,
} as any)
const _homeContactMeRoute = _homeContactMeRouteImport.update({
  id: '/contact-me',
  path: '/contact-me',
  getParentRoute: () => _homeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof _homeIndexRoute
  '/contact-me': typeof _homeContactMeRoute
  '/gaming': typeof _homeGamingRoute
  '/my-bio': typeof _homeMyBioRoute
  '/my-projects': typeof _homeMyProjectsRoute
  '/my-socials': typeof _homeMySocialsRoute
  '/my-stack': typeof _homeMyStackRoute
  '/timeline': typeof _homeTimelineRoute
}
export interface FileRoutesByTo {
  '/contact-me': typeof _homeContactMeRoute
  '/gaming': typeof _homeGamingRoute
  '/my-bio': typeof _homeMyBioRoute
  '/my-projects': typeof _homeMyProjectsRoute
  '/my-socials': typeof _homeMySocialsRoute
  '/my-stack': typeof _homeMyStackRoute
  '/timeline': typeof _homeTimelineRoute
  '/': typeof _homeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__home': typeof _homeRouteRouteWithChildren
  '/__home/contact-me': typeof _homeContactMeRoute
  '/__home/gaming': typeof _homeGamingRoute
  '/__home/my-bio': typeof _homeMyBioRoute
  '/__home/my-projects': typeof _homeMyProjectsRoute
  '/__home/my-socials': typeof _homeMySocialsRoute
  '/__home/my-stack': typeof _homeMyStackRoute
  '/__home/timeline': typeof _homeTimelineRoute
  '/__home/': typeof _homeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact-me'
    | '/gaming'
    | '/my-bio'
    | '/my-projects'
    | '/my-socials'
    | '/my-stack'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contact-me'
    | '/gaming'
    | '/my-bio'
    | '/my-projects'
    | '/my-socials'
    | '/my-stack'
    | '/timeline'
    | '/'
  id:
    | '__root__'
    | '/__home'
    | '/__home/contact-me'
    | '/__home/gaming'
    | '/__home/my-bio'
    | '/__home/my-projects'
    | '/__home/my-socials'
    | '/__home/my-stack'
    | '/__home/timeline'
    | '/__home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _homeRouteRoute: typeof _homeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__home': {
      id: '/__home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _homeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__home/': {
      id: '/__home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _homeIndexRouteImport
      parentRoute: typeof _homeRouteRoute
    }
    '/__home/timeline': {
      id: '/__home/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof _homeTimelineRouteImport
      parentRoute: typeof _homeRouteRoute
    }
    '/__home/my-stack': {
      id: '/__home/my-stack'
      path: '/my-stack'
      fullPath: '/my-stack'
      preLoaderRoute: typeof _homeMyStackRouteImport
      parentRoute: typeof _homeRouteRoute
    }
    '/__home/my-socials': {
      id: '/__home/my-socials'
      path: '/my-socials'
      fullPath: '/my-socials'
      preLoaderRoute: typeof _homeMySocialsRouteImport
      parentRoute: typeof _homeRouteRoute
    }
    '/__home/my-projects': {
      id: '/__home/my-projects'
      path: '/my-projects'
      fullPath: '/my-projects'
      preLoaderRoute: typeof _homeMyProjectsRouteImport
      parentRoute: typeof _homeRouteRoute
    }
    '/__home/my-bio': {
      id: '/__home/my-bio'
      path: '/my-bio'
      fullPath: '/my-bio'
      preLoaderRoute: typeof _homeMyBioRouteImport
      parentRoute: typeof _homeRouteRoute
    }
    '/__home/gaming': {
      id: '/__home/gaming'
      path: '/gaming'
      fullPath: '/gaming'
      preLoaderRoute: typeof _homeGamingRouteImport
      parentRoute: typeof _homeRouteRoute
    }
    '/__home/contact-me': {
      id: '/__home/contact-me'
      path: '/contact-me'
      fullPath: '/contact-me'
      preLoaderRoute: typeof _homeContactMeRouteImport
      parentRoute: typeof _homeRouteRoute
    }
  }
}

interface _homeRouteRouteChildren {
  _homeContactMeRoute: typeof _homeContactMeRoute
  _homeGamingRoute: typeof _homeGamingRoute
  _homeMyBioRoute: typeof _homeMyBioRoute
  _homeMyProjectsRoute: typeof _homeMyProjectsRoute
  _homeMySocialsRoute: typeof _homeMySocialsRoute
  _homeMyStackRoute: typeof _homeMyStackRoute
  _homeTimelineRoute: typeof _homeTimelineRoute
  _homeIndexRoute: typeof _homeIndexRoute
}

const _homeRouteRouteChildren: _homeRouteRouteChildren = {
  _homeContactMeRoute: _homeContactMeRoute,
  _homeGamingRoute: _homeGamingRoute,
  _homeMyBioRoute: _homeMyBioRoute,
  _homeMyProjectsRoute: _homeMyProjectsRoute,
  _homeMySocialsRoute: _homeMySocialsRoute,
  _homeMyStackRoute: _homeMyStackRoute,
  _homeTimelineRoute: _homeTimelineRoute,
  _homeIndexRoute: _homeIndexRoute,
}

const _homeRouteRouteWithChildren = _homeRouteRoute._addFileChildren(
  _homeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _homeRouteRoute: _homeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
